Repository GodotECS/godex, pull requests merged in 2021-06, with the labels that each got.

#177 Improve the ScriptEcs mechanism
  ecs.cpp
  ecs.h
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/entity_editor_plugin.cpp
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  modules/godot/nodes/entity.h
  modules/godot/nodes/script_ecs.cpp
  modules/godot/nodes/script_ecs.h
  modules/godot/nodes/shared_component_resource.cpp
  pipeline/descriptors.h
  pipeline/pipeline_builder.cpp
  pipeline/pipeline_builder.h
  tests/test_ecs_base.h
  tests/test_ecs_pipeline_builder.h
  tests/test_ecs_query.h
  tests/test_ecs_spawner.h
  tests/test_ecs_system.h
  tests/test_ecs_world.h
  tests/test_utilities.h
Labels: enhancement

#178 Removes the extra script instantiation used by the component to get the defaults.
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/script_ecs.cpp
Labels: enhancement

#179 Completed System dependency registration and more.
  ecs.cpp
  ecs.h
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/script_ecs.cpp
  modules/godot/nodes/script_ecs.h
  pipeline/descriptors.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  tests/test_ecs_spawner.h
  tests/test_ecs_system.h
  tests/test_utilities.h
Labels: enhancement

#180 Refactored the entire Pipeline class.
  ecs.cpp
  ecs.h
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  pipeline/pipeline_builder.cpp
  pipeline/pipeline_builder.h
  storage/hierarchical_storage.h
  storage/storage.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  tests/test_ecs_pipeline.h
  tests/test_ecs_pipeline_builder.h
  tests/test_ecs_spawner.h
  tests/test_ecs_system.h
  tests/test_ecs_temporary_system.h
  world/world.h
Labels: enhancement

#182 PipelineBuilder Unit Test feast and finalization.
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  pipeline/pipeline_builder.cpp
  pipeline/pipeline_builder.h
  tests/test_ecs_pipeline_builder.h
Labels: enhancement

#184 Add support to SystemBundle
  ecs.cpp
  ecs.h
  modules/bullet_physics/register_types.cpp
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/editor_world_ecs.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  modules/godot/register_types.cpp
Labels: enhancement, topic:editor

#186 Add Pipeline view
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/editor_world_ecs.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
Labels: enhancement, topic:editor

#189 Improved pipeline composition, add dispatcher concept.
  SCsub
  ecs.cpp
  ecs.h
  methods_ecs.py
  modules/bullet_physics/register_types.cpp
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  modules/godot/register_types.cpp
  modules/godot/systems/physics_process_system.cpp
  modules/godot/systems/physics_process_system.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  pipeline/pipeline_builder.cpp
  pipeline/pipeline_builder.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  systems/system.h
  systems/system_builder.h
  tests/test_ecs_pipeline.h
  tests/test_ecs_pipeline_builder.h
  tests/test_ecs_system.h
Labels: enhancement, has docs, topic:ecs, topic:godot_integration, topic:syntax

#190 Removed debug print on entity prop change.
  modules/godot/nodes/entity.h
Labels: enhancement, topic:editor

#191 WorldECS usage enhancement
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  modules/godot/register_types.cpp
Labels: enhancement, topic:editor

#192 Add pipeline errors and warnings visualization.
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/editor_world_ecs.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  modules/godot/nodes/script_ecs.cpp
  modules/godot/nodes/script_ecs.h
  pipeline/pipeline_builder.cpp
Labels: enhancement, topic:editor

#193 Add warning to notify that a system is invalid and being excluded.
  pipeline/pipeline_builder.cpp
Labels: enhancement, topic:editor

#194 Implemented the Pipeline Viewer HUD
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/editor_world_ecs.h
  pipeline/pipeline_builder.cpp
Labels: enhancement, topic:editor

#197 Suppress false positive uncatched bullet physics changed event.
  ecs.cpp
  ecs.h
  modules/bullet_physics/register_types.cpp
  modules/bullet_physics/systems_base.cpp
  modules/bullet_physics/systems_base.h
  modules/bullet_physics/systems_walk.cpp
  pipeline/pipeline_builder.cpp
  tests/test_ecs_pipeline_builder.h
Labels: bug, enhancement, topic:editor

#195 Renames to get up to speed with master
  modules/bullet_physics/bullet_types_converter.cpp
  modules/bullet_physics/bullet_types_converter.h
  modules/bullet_physics/components_gizmos.cpp
  modules/bullet_physics/systems_base.cpp
  modules/godot/components/transform_component.cpp
  modules/godot/components/transform_component.h
  modules/godot/editor_plugins/components_gizmo_3d.h
  modules/godot/editor_plugins/components_mesh_gizmo_3d.cpp
  modules/godot/editor_plugins/components_mesh_gizmo_3d.h
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/entity_editor_plugin.cpp
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/entity.h
  modules/godot/nodes/script_ecs.cpp
  modules/godot/nodes/shared_component_resource.cpp
  pipeline/pipeline_builder.cpp
  pipeline/pipeline_builder.h
  register_types.cpp
  tests/test_ecs_query.h
  tests/test_ecs_storage_hierarchical.h
  tests/test_ecs_system.h
  tests/test_ecs_world.h
  tests/test_utilities.h
Labels: enhancement, good first issue, topic:godot_integration
