Repository GodotECS/godex, pull requests merged in 2021-07, with the labels that each got.

#200 Fix inspector not showing scripted component properties
  modules/godot/editor_plugins/entity_editor_plugin.cpp
Labels: bug, topic:editor

#201 Removes the code to show scripted components
  modules/godot/editor_plugins/entity_editor_plugin.cpp
Labels: bug, topic:editor

#202 Fix scripted component scene storage.
  modules/godot/nodes/entity.h
Labels: bug, topic:editor

#196 Timers
  modules/godot/databags/databag_timer.cpp
  modules/godot/databags/databag_timer.h
  modules/godot/databags/godot_engine_databags.h
  modules/godot/register_types.cpp
  tests/test_ecs_databag_timer.h
Labels: enhancement, topic:ecs, topic:feature

#199 Introducing the new event mechanism
  SCsub
  components/component.h
  databags/databag.h
  ecs.cpp
  ecs.h
  ecs_types.cpp
  ecs_types.h
  events/events.h
  iterators/dynamic_query.cpp
  iterators/dynamic_query.h
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/ecs_utilities.h
  modules/godot/nodes/ecs_world.cpp
  modules/godot/nodes/ecs_world.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  pipeline/pipeline_builder.cpp
  register_types.cpp
  storage/event_storage.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  systems/system.h
  systems/system_builder.h
  tests/test_ecs_pipeline_builder.h
  tests/test_ecs_query.h
  tests/test_ecs_system.h
  thirdparty/typestring.hh
  utils/fetchers.cpp
  utils/fetchers.h
  world/world.cpp
  world/world.h
Labels: enhancement, topic:ecs

#207 Correctly exposes transform basis
  modules/godot/components/transform_component.cpp
Labels: bug

#209 Refactor the area overlap event
  modules/bullet_physics/components_area.cpp
  modules/bullet_physics/components_area.h
  modules/bullet_physics/components_generic.h
  modules/bullet_physics/register_types.cpp
  modules/bullet_physics/systems_base.cpp
  modules/bullet_physics/systems_base.h
  pipeline/pipeline_builder.cpp
Labels: enhancement, topic:ecs

#210 Improve mesh rendering update
  modules/bullet_physics/databag_space.cpp
  modules/godot/components/mesh_component.cpp
  modules/godot/components/mesh_component.h
  modules/godot/editor_plugins/components_mesh_gizmo_3d.cpp
  modules/godot/nodes/entity.h
  modules/godot/systems/mesh_updater_system.cpp
Labels: enhancement

#211 Renamed the area enter event.
  events/events.h
  iterators/events_emitter_receiver.h
  modules/bullet_physics/components_area.cpp
  modules/bullet_physics/components_area.h
  modules/bullet_physics/events_generic.cpp
  modules/bullet_physics/events_generic.h
  modules/bullet_physics/register_types.cpp
  modules/bullet_physics/systems_base.cpp
  modules/bullet_physics/systems_base.h
  systems/system_builder.h
  tests/test_ecs_pipeline_builder.h
Labels: enhancement

#212 Register godex in the pre_register.
  components/component.h
  ecs_types.h
  register_types.cpp
  register_types.h
Labels: bug

#213 Add New UI to the new Event mechanism.
  ecs.cpp
  ecs.h
  ecs_types.h
  modules/bullet_physics/components_area.cpp
  modules/godot/editor_plugins/entity_editor_plugin.cpp
  systems/dynamic_system.cpp
Labels: enhancement, topic:ecs

#214 Hide the `parent` property from `Child` component.
  components/child.cpp
Labels: enhancement, topic:godot_integration

#215 Fix some crashes triggered by using the API in the wrong way on GDScript
  iterators/dynamic_query.cpp
  modules/godot/nodes/ecs_world.cpp
Labels: bug

#216 Fix Entity3D transform when parented with a Node3D.
  modules/godot/nodes/entity.h
Labels: bug, topic:editor

#217 Using the new SNAME optimization.
  README.md
  modules/godot/editor_plugins/components_mesh_gizmo_3d.cpp
  modules/godot/editor_plugins/components_mesh_gizmo_3d.h
  modules/godot/editor_plugins/editor_world_ecs.cpp
  modules/godot/editor_plugins/entity_editor_plugin.cpp
  modules/godot/nodes/ecs_utilities.cpp
  modules/godot/nodes/entity.h
  register_types.cpp
  systems/dynamic_system.cpp
  systems/dynamic_system.h
Labels: enhancement, topic:godot_integration

#235 Exposed SharedResource::init and changed Entity icon
  icons/Entity2D.svg
  icons/Entity3D.svg
  modules/godot/nodes/shared_component_resource.cpp
Labels: topic:editor

#238 Removed some component event left over code
  ecs.h
  ecs_types.h
Labels: topic:build

#237 Edition custom property arrays
  components/dynamic_component.cpp
  components/dynamic_component.h
  ecs.cpp
  ecs.h
  ecs_types.h
  modules/godot/register_types.cpp
Labels: Hero!, topic:ecs, topic:feature, topic:godot_integration
