Repository GodotECS/godex, pull requests merged in 2021-02, with the labels that each got.

#74 Hierarchy [WIP]
  components/child.cpp
  components/child.h
  components/component.h
  ecs.cpp
  ecs.h
  ecs_types.h
  godot/components/child.h
  godot/components/disabled.cpp
  godot/components/transform_component.cpp
  godot/components/transform_component.h
  godot/nodes/ecs_utilities.cpp
  godot/nodes/ecs_utilities.h
  godot/nodes/ecs_world.cpp
  godot/nodes/entity.h
  godot/systems/mesh_updater_system.cpp
  iterators/dynamic_query.cpp
  iterators/dynamic_query.h
  iterators/query.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  register_types.cpp
  storage/batch_storage.h
  storage/dense_vector.h
  storage/hierarchical_storage.h
  storage/storage.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  tests/test_ecs_base.h
  tests/test_ecs_query.h
  tests/test_ecs_storage_hierarchical.h
  tests/test_ecs_system.h
  tests/test_ecs_temporary_system.h
  tests/test_ecs_world.h
  world/world.cpp
  world/world.h
Labels: enhancement, topic:feature

#75 External documentation can now be made, Syncs with repo's Wiki
  .github/workflows/update_wiki.yml
  config.py
  doc_classes/Component.xml
  doc_classes/DynamicQuery.xml
  doc_classes/ECS.xml
  doc_classes/Entity.xml
  doc_classes/PipelineECS.xml
  doc_classes/System.xml
  doc_classes/WorldECS.xml
Labels: Hero!, enhancement, topic:editor

#76 Using user GodexBot and added suffix `_class`
  .github/workflows/update_wiki.yml
Labels: topic:CI, topic:wiki

#77 Added doc on WorldECS::add_component API
  doc_classes/WorldECS.xml
Labels: topic:documentation

#81 Simplify GDScript exposure and make Component and Databag trivial.
  components/child.cpp
  components/child.h
  components/component.cpp
  components/component.h
  components/dynamic_component.cpp
  components/dynamic_component.h
  databags/databag.cpp
  databags/databag.h
  ecs.cpp
  ecs.h
  ecs_types.cpp
  ecs_types.h
  godot/components/disabled.h
  godot/components/mesh_component.cpp
  godot/components/mesh_component.h
  godot/components/physics/shape_3d_component.h
  godot/components/transform_component.h
  godot/nodes/ecs_world.cpp
  godot/nodes/ecs_world.h
  godot/nodes/entity.h
  iterators/dynamic_query.cpp
  iterators/dynamic_query.h
  storage/dense_vector.h
  storage/storage.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  tests/test_ecs_pipeline.h
  tests/test_ecs_query.h
  tests/test_ecs_storage_dense_vector.h
  tests/test_ecs_system.h
  tests/test_ecs_world.h
Labels: enhancement, topic:performances

#82 Added warn if the registered component is not trivial.
  ecs.h
  godot/components/transform_component.h
Labels: enhancement, topic:performances

#84 Exposed the spatiality concept to Entity node
  godot/databags/godot_engine_databags.h
  godot/nodes/entity.cpp
  godot/nodes/entity.h
Labels: enhancement, topic:godot_integration

#86 Optimized the ChangeList
  ecs_types.h
  godot/systems/physics_process_system.cpp
  storage/storage.h
  tests/test_ecs_base.h
  tests/test_ecs_change_list.h
  world/world.h
Labels: enhancement, topic:performances

#89 Changed filter.
  SCsub
  godot/components/mesh_component.cpp
  godot/components/mesh_component.h
  godot/components/transform_component.cpp
  godot/components/transform_component.h
  godot/databags/visual_servers_databags.cpp
  godot/databags/visual_servers_databags.h
  godot/editor_plugins/editor_world_ecs.cpp
  godot/nodes/ecs_utilities.cpp
  godot/nodes/ecs_utilities.h
  godot/nodes/ecs_world.cpp
  godot/systems/mesh_updater_system.cpp
  godot/systems/mesh_updater_system.h
  iterators/dynamic_query.cpp
  iterators/dynamic_query.h
  iterators/query.h
  pipeline/pipeline.cpp
  pipeline/pipeline.h
  storage/batch_storage.h
  storage/dense_vector.h
  storage/entity_list.cpp
  storage/entity_list.h
  storage/hierarchical_storage.h
  storage/storage.h
  systems/dynamic_system.cpp
  systems/dynamic_system.h
  systems/system.h
  systems/system_builder.h
  tests/test_ecs_entity_list.h
  tests/test_ecs_pipeline.h
  tests/test_ecs_query.h
  tests/test_ecs_storage_dense_vector.h
  tests/test_ecs_storage_hierarchical.h
  tests/test_ecs_system.h
  tests/test_ecs_world.h
Labels: enhancement, topic:feature

#93 Added linux CI and compile badge in the README.md
  .github/workflows/linux_builds.yml
  README.md
  storage/hierarchical_storage.h
  storage/storage.h
Labels: os:linux, topic:CI

#95 Fixed code style.
  .github/workflows/linux_builds.yml
  .github/workflows/static_checks.yml
  .github/workflows/update_wiki.yml
  .github/workflows/windows_builds.yml
  components/component.h
  components/dynamic_component.cpp
  config.py
  databags/databag.h
  ecs_types.h
  godot/editor_plugins/entity_editor_plugin.cpp
  iterators/dynamic_query.h
  iterators/query.cpp
  methods_ecs.py
  misc/scripts/clang_format.sh
  systems/dynamic_system.h
  systems/system_builder.h
  tests/test_ecs_base.h
  tests/test_ecs_storage_hierarchical.h
  tests/test_ecs_system.h
  tests/test_ecs_world.h
Labels: topic:CI, topic:syntax

#96 Improved Query syntax and optimized fetch.
  godot/systems/mesh_updater_system.cpp
  iterators/query.h
  storage/entity_list.cpp
  storage/entity_list.h
  storage/hierarchical_storage.h
  storage/storage.h
  tests/test_ecs_query.h
  tests/test_ecs_system.h
Labels: enhancement, topic:performances, topic:syntax

#97 Optimized DynamicQuery (script) and added some new features.
  iterators/dynamic_query.cpp
  iterators/dynamic_query.h
  systems/dynamic_system.cpp
  tests/test_ecs_query.h
  tests/test_ecs_system.h
  world/world.cpp
  world/world.h
Labels: enhancement, topic:performances, topic:script

#98 Improved ECS editor
  godot/editor_plugins/editor_world_ecs.cpp
  godot/editor_plugins/editor_world_ecs.h
  icons/ECS.svg
Labels: enhancement, topic:editor

#99 Added SteadyStorage. Put DenseVectorStorage in its own file
  components/component.h
  storage/dense_vector.h
  storage/dense_vector_storage.h
  storage/steady_storage.h
  tests/test_ecs_paged_vector.h
  tests/test_ecs_storage_dense_vector.h
Labels: enhancement, topic:feature

#102 Added shared steady storage.
  ecs_types.h
  storage/shared_steady_storage.h
  storage/storage.h
  tests/test_ecs_storage_shared_steady.h
  tests/test_ecs_storage_steady.h
Labels: enhancement, topic:feature

#103 Added possibility to config per component Storage.
  components/child.cpp
  components/child.h
  ecs.cpp
  ecs.h
  ecs_types.h
  godot/components/transform_component.cpp
  godot/components/transform_component.h
  godot/nodes/ecs_world.cpp
  godot/nodes/ecs_world.h
  storage/dense_vector.h
  storage/dense_vector_storage.h
  storage/hierarchical_storage.h
  storage/shared_steady_storage.h
  storage/steady_storage.h
  storage/storage.h
  tests/test_ecs_storage_shared_steady.h
  tests/test_ecs_storage_steady.h
  world/world.cpp
  world/world.h
Labels: enhancement, topic:performances
